version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    environment:
      - VITE_GIPHY_API_KEY=R8W7zlVPaABPJARkY0G3z543Ue2Apd4g
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5050:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/pokemon_data
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
